name: Update Version
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install npm dependencies
        run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog -D @semantic-release/exec
      - name: Run semantic release
        run: npx semantic-release
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}

