name: Update Version
on:
  push:
    branches: [ master ]
    paths:
      - 'apps/buyer_app/**'
  workflow_dispatch:


jobs:
  update_version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install npm dependencies
        run: npm install
      - name: Run semantic release
        run: npx semantic-release
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
  ARGS: "-av"

