name: Update Version
on:
  push:
    branches: [ master ]
    paths:
      - 'apps/buyer_app/**'
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN}}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}

jobs:
  update_version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Temporarily disable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: always()
        with:
          access_token: ${{ secrets.GH_TOKEN} }}
          branch: ${{ github.event.repository.default_branch }}

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Setup melos
        run: dart pub global activate melos

      - name: Setup cider
        run: dart pub global activate cider

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Get packages
        run: melos bootstrap

      - name: Run semantic release
        run: npx semantic-release

      - name: Enable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: always()  # Force to always run this step to ensure "include administrators" is always turned back on
        with:
          access_token: ${{ secrets.GH_TOKEN} }}
          owner: benjefferies
          repo: branch-protection-bot
          branch: ${{ github.event.repository.default_branch }}



