name: Update Version
on:
  push:
    branches: [ master ]
    paths:
      - 'apps/buyer_app/**'
  workflow_dispatch:


jobs:
  update_version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Setup melos
        run: dart pub global activate melos

      - name: Setup cider
        run: dart pub global activate cider

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Get packages
        run: melos bootstrap

      - name: Run semantic release
        run: npx semantic-release
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}


